### ISSUE TITLE
해당 레포지토리 삭제 요청

### ISSUE THREAD

**Issue by dytroc** [highright1234/senior-center-twerk-machine#1]
해당 레포는 깃허브 이용자들에게 불쾌감을 주어 원활한 서비스 이용에 차질을 일으켰습니다.

그렇기에 3일 내로 해당 레포를 내려줬으면 좋을 거 같습니다.

**Comment by highright1234** [comment]
~~쇼토코노코로 이름 안한걸 다행으로 생각하세요~~

**Comment by highright1234** [comment]
이렇게 된거 님도 이 플러그인 써보실레유? 릴리즈에 올려놨습니다 ㅋㅋ

**Comment by dytroc** [comment]
??
